// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using story_web.Data;

#nullable disable

namespace story_web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260512173042_AddAuthorFollowers")]
    partial class AddAuthorFollowers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("story_web.Models.Author", b =>
                {
                    b.Property<int>("id_Author")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_Author"));

                    b.Property<string>("Avatar")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PenName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("id_User")
                        .HasColumnType("int");

                    b.HasKey("id_Author");

                    b.HasIndex("id_User")
                        .IsUnique()
                        .HasFilter("[id_User] IS NOT NULL");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("story_web.Models.AuthorFollower", b =>
                {
                    b.Property<int>("id_AuthorFollower")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_AuthorFollower"));

                    b.Property<DateTime?>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<int?>("id_Author")
                        .HasColumnType("int");

                    b.Property<int?>("id_User")
                        .HasColumnType("int");

                    b.HasKey("id_AuthorFollower");

                    b.HasIndex("id_Author");

                    b.HasIndex("id_User");

                    b.ToTable("AuthorFollowers");
                });

            modelBuilder.Entity("story_web.Models.Category", b =>
                {
                    b.Property<int>("id_Category")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_Category"));

                    b.Property<string>("CategoryName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_Category");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("story_web.Models.Chapter", b =>
                {
                    b.Property<int>("id_Chapter")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_Chapter"));

                    b.Property<string>("AISummary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AudioPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChapterName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal?>("ChapterNumber")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Modified_At")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Posted_At")
                        .HasColumnType("datetime2");

                    b.Property<int?>("id_Story")
                        .HasColumnType("int");

                    b.HasKey("id_Chapter");

                    b.HasIndex("id_Story");

                    b.ToTable("Chapters");
                });

            modelBuilder.Entity("story_web.Models.Comment", b =>
                {
                    b.Property<int>("id_Comment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_Comment"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Posted_At")
                        .HasColumnType("datetime2");

                    b.Property<int?>("id_Story")
                        .HasColumnType("int");

                    b.Property<int?>("id_User")
                        .HasColumnType("int");

                    b.HasKey("id_Comment");

                    b.HasIndex("id_Story");

                    b.HasIndex("id_User");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("story_web.Models.Favourite", b =>
                {
                    b.Property<int>("id_Favourite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_Favourite"));

                    b.Property<DateTime?>("Added_At")
                        .HasColumnType("datetime2");

                    b.Property<int?>("id_Story")
                        .HasColumnType("int");

                    b.Property<int?>("id_User")
                        .HasColumnType("int");

                    b.HasKey("id_Favourite");

                    b.HasIndex("id_Story");

                    b.HasIndex("id_User");

                    b.ToTable("Favourites");
                });

            modelBuilder.Entity("story_web.Models.Notification", b =>
                {
                    b.Property<int>("id_Noti")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_Noti"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsRead")
                        .HasColumnType("bit");

                    b.Property<int?>("id_User")
                        .HasColumnType("int");

                    b.HasKey("id_Noti");

                    b.HasIndex("id_User");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("story_web.Models.ReadingHistory", b =>
                {
                    b.Property<int>("id_History")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_History"));

                    b.Property<DateTime?>("Last_Read_At")
                        .HasColumnType("datetime2");

                    b.Property<int?>("id_Chapter")
                        .HasColumnType("int");

                    b.Property<int?>("id_Story")
                        .HasColumnType("int");

                    b.Property<int?>("id_User")
                        .HasColumnType("int");

                    b.HasKey("id_History");

                    b.HasIndex("id_Chapter");

                    b.HasIndex("id_Story");

                    b.HasIndex("id_User");

                    b.ToTable("Reading_History");
                });

            modelBuilder.Entity("story_web.Models.Story", b =>
                {
                    b.Property<int>("id_Story")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_Story"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("Modified_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("PostStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Posted_At")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("Reject_Reason")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("StoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StoryStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Views")
                        .HasColumnType("int");

                    b.Property<int?>("id_Author")
                        .HasColumnType("int");

                    b.HasKey("id_Story");

                    b.HasIndex("id_Author");

                    b.ToTable("Stories");
                });

            modelBuilder.Entity("story_web.Models.StoryCategory", b =>
                {
                    b.Property<int>("id_Story")
                        .HasColumnType("int");

                    b.Property<int>("id_Category")
                        .HasColumnType("int");

                    b.HasKey("id_Story", "id_Category");

                    b.HasIndex("id_Category");

                    b.ToTable("StoryCategories");
                });

            modelBuilder.Entity("story_web.Models.User", b =>
                {
                    b.Property<int>("id_User")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_User"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("modified_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Password");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id_User");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("story_web.Models.Author", b =>
                {
                    b.HasOne("story_web.Models.User", "User")
                        .WithOne("Author")
                        .HasForeignKey("story_web.Models.Author", "id_User")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("story_web.Models.AuthorFollower", b =>
                {
                    b.HasOne("story_web.Models.Author", "Author")
                        .WithMany("Followers")
                        .HasForeignKey("id_Author")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("story_web.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("id_User");

                    b.Navigation("Author");

                    b.Navigation("User");
                });

            modelBuilder.Entity("story_web.Models.Chapter", b =>
                {
                    b.HasOne("story_web.Models.Story", "Story")
                        .WithMany("Chapters")
                        .HasForeignKey("id_Story")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Story");
                });

            modelBuilder.Entity("story_web.Models.Comment", b =>
                {
                    b.HasOne("story_web.Models.Story", "Story")
                        .WithMany()
                        .HasForeignKey("id_Story");

                    b.HasOne("story_web.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("id_User");

                    b.Navigation("Story");

                    b.Navigation("User");
                });

            modelBuilder.Entity("story_web.Models.Favourite", b =>
                {
                    b.HasOne("story_web.Models.Story", "Story")
                        .WithMany()
                        .HasForeignKey("id_Story")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("story_web.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("id_User")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Story");

                    b.Navigation("User");
                });

            modelBuilder.Entity("story_web.Models.Notification", b =>
                {
                    b.HasOne("story_web.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("id_User")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("story_web.Models.ReadingHistory", b =>
                {
                    b.HasOne("story_web.Models.Chapter", "Chapter")
                        .WithMany()
                        .HasForeignKey("id_Chapter")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("story_web.Models.Story", "Story")
                        .WithMany()
                        .HasForeignKey("id_Story")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("story_web.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("id_User")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Chapter");

                    b.Navigation("Story");

                    b.Navigation("User");
                });

            modelBuilder.Entity("story_web.Models.Story", b =>
                {
                    b.HasOne("story_web.Models.Author", "Author")
                        .WithMany("Stories")
                        .HasForeignKey("id_Author")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Author");
                });

            modelBuilder.Entity("story_web.Models.StoryCategory", b =>
                {
                    b.HasOne("story_web.Models.Category", "Category")
                        .WithMany("StoryCategories")
                        .HasForeignKey("id_Category")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("story_web.Models.Story", "Story")
                        .WithMany("StoryCategories")
                        .HasForeignKey("id_Story")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Story");
                });

            modelBuilder.Entity("story_web.Models.Author", b =>
                {
                    b.Navigation("Followers");

                    b.Navigation("Stories");
                });

            modelBuilder.Entity("story_web.Models.Category", b =>
                {
                    b.Navigation("StoryCategories");
                });

            modelBuilder.Entity("story_web.Models.Story", b =>
                {
                    b.Navigation("Chapters");

                    b.Navigation("StoryCategories");
                });

            modelBuilder.Entity("story_web.Models.User", b =>
                {
                    b.Navigation("Author");

                    b.Navigation("Comments");

                    b.Navigation("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
